apiVersion: apps/v1
kind: Deployment
metadata:
  name: cellgame-deployment
  labels:
    app: cellgame
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cellgame
  template:
    metadata:
      labels:
        app: cellgame
    spec:
      containers:
      - name: cellgame
        image: sprngio/cellgame:latest
        ports:
        - containerPort: 80